---
title: "JSC370 Final Project"
author: "Steven Liu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(plotly)
library(knitr)
library(widgetframe)
```

```{r, echo=FALSE}
cv_states_readin <- 
  data.table::fread("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
state_pops <- data.table::fread("https://raw.githubusercontent.com/COVID19Tracking/associated-data/master/us_census_data/us_census_2018_population_estimates_states.csv")
state_pops$abb <- state_pops$state
state_pops$state <- state_pops$state_name
state_pops$state_name <- NULL
cv_states <- merge(cv_states_readin, state_pops, by="state")
```


```{r, echo=FALSE}
cv_states$date <- as.Date(cv_states$date, format="%Y-%m-%d")
state_list <- unique(cv_states$state)
cv_states$state <- factor(cv_states$state, levels = state_list)
abb_list <- unique(cv_states$abb)
cv_states$abb <- factor(cv_states$abb, levels = abb_list)
cv_states = cv_states[order(cv_states$state, cv_states$date),]
```

  
```{r, echo=FALSE}
cv_states <- cv_states %>% 
  group_by(state) %>% 
  mutate(
    new_cases = c(-9999, diff(cases)),
    new_deaths = c(-9999, diff(deaths))
  ) %>% 
  mutate(
    new_cases = ifelse(new_cases == -9999, cases, new_cases),
    new_deaths = ifelse(new_deaths == -9999, deaths, new_deaths)
  )
```

```{r, echo=FALSE}
cv_states  <- cv_states %>% filter(date >= '2022-10-01')
```
  

```{r, echo=FALSE}
cv_states <- cv_states %>% mutate(
  new_cases = ifelse(new_cases < 0, 0, new_cases),
  new_deaths = ifelse(new_deaths < 0, 0, new_deaths)
)


```


```{r, echo=FALSE}
cv_states <- cv_states %>% 
  mutate(
    per100k = round(cases / population * 1e5, digits = 1),
    newper100k = round(new_cases / population * 1e5, digits = 1),
    deathsper100k = round(deaths / population * 1e5, digits = 1),
    newdeathsper100k = round(new_deaths / population * 1e5, digits = 1)
  )

```

```{r, echo=FALSE}
cv_states <- cv_states %>% mutate(
  naive_cfr = deaths / cases
)
```

```{r, echo=FALSE}
cv_states_today <- cv_states %>% filter(date == max(cv_states$date))
```

```{r, echo=FALSE}
p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```


## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
p1_scatter
```

### Figure 2

```{r echo=FALSE}
p2_scatter
```

{-}